[git]
username = "m-correa"
repository_name = "Puppet"
project_id = "60942723"
personal_access_token = ""
repository_url = ""
repository_url_ssh = ""
gitlab_api_url = "https://gitlab.com/api/v4"
git_hosts = [
    "gitlab.com",
]

[git_anim]
username = "m-correa"
repository_name = "Puppet_anim"
project_id = "60945745"
personal_access_token = ""
repository_url = ""
repository_url_ssh = ""
gitlab_api_url = "https://gitlab.com/api/v4"
git_hosts = [
    "gitlab.com",
]

[general]
working_path = ""
animator_path = ""
repository_prefix = "PuppetLauncher/workspaces/"
maya25_path = "
maya24_path = "C://Program Files/Autodesk/Maya2024/bin/maya.exe"
maya22_path = "C://Program Files/Autodesk/Maya2022/bin/maya.exe"
git_path = "C://Program Files/Git/git-cmd.exe"
git_installer_url = "https://github.com/git-for-windows/git/releases/download/v2.41.0.windows.1/Git-2.41.0-64-bit.exe"
python2_installer_url = "https://www.python.org/ftp/python/2.7.18/python-2.7.18.amd64.msi"
selected_maya_bat = "C:\\Users\\m-correa\\PycharmProjects\\PuppetLauncher/workspaces/default\\Tempura\\AdminMaya2023.bat"
selected_bat = "C:\\Users\\m-correa\\PycharmProjects\\PuppetLauncher/workspaces/default\\Tempura"
python2_alias = ""

[db.roles]
names = [
    "admin",
    "dev",
    "animator",
]
default_role = "animator"

[db.users]
user_names = [
    "m-correa",
]
default_password = "1234"
emails = [
    "example@example.com"
]
roles = [
    "admin",
    "admin",
]

[test]
debug = false
debug_user = "m-correa"

[projects]
projects = [
    "EDO",
    "N1",
]
