[git]
username = "m-correa"
repository_name="testpository"
personal_access_token= "glpat-RpDVxM2RPLz7zQvQZ9Cx"
repository_url = "https://m-correa:glpat-RpDVxM2RPLz7zQvQZ9Cx@gitlab.com/m-correa/testrespository.git"

[general]
working_path = 'D://RiggingLauncher/workingSpaces/default/'
