# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    [
        'App.py',
        'main.py',
        'Controller/GitController.py',
        'Controller/GitProtocol/GitProtocols.py',
        'Controller/GitProtocol/__init__.py',
        'Controller/SystemController.py',
        'Controller/__init__.py',
        'Exceptions/AppExceptions.py',
        'Model/FileLockModel.py',
        'Model/UserModel.py',
        'Model/UserRolesModel.py',
        'Model/__init__.py',
        'Utils/DataBaseConnection.py',
        'Utils/DataBaseManager.py',
        'Utils/Environment.py',
        'Utils/FileManager.py',
        'Utils/SignalManager.py',
        'Utils/SingletonMeta.py',
        'Utils/UserSession.py',
        'Utils/__init__.py',
        'View/BaseWindow.py',
        'View/CustomStyleSheetApplier.py',
        'View/LauncherWindow.py',
        'View/UIAdminUserList.py',
        'View/UIAdminWidget.py',
        'View/UIChangesList.py',
        'View/UICommitWindow.py',
        'View/UIDiffsWidget.py',
        'View/UIGitTab.py',
        'View/UILoadingWidget.py',
        'View/UILogger.py',
        'View/UILoginWindow.py',
        'View/UIManager.py',
        'View/UIMergeRequestTab.py',
        'View/UIRepViewer.py',
        'View/UISessionWidget.py',
        'View/UISignupWindow.py',
        'View/WindowID.py',
        'View/__init__.py'
    ],
    pathex=['.'],
    binaries=[],
    datas=[
        ('View/', 'View/'),
        ('Controller/', 'Controller/'),
        ('Controller/GitProtocol', 'Controller/GitProtocol'),
        ('Model/', 'Model/'),
        ('Exceptions/', 'Exceptions/'),
        ('Resources/', 'Resources/'),
        ('Resources/Img', 'Resources/Img'),
        ('Resources/Img/arrowDown.png', 'Resources/Img/'),
        ('Resources/Img/arrowUp.png', 'Resources/Img/'),
        ('Resources/Img/checkmark.png', 'Resources/Img/'),
        ('Resources/Img/cross.png', 'Resources/Img/'),
        ('Resources/Img/default_icon.ico', 'Resources/Img/'),
        ('Resources/Img/mayaico.png', 'Resources/Img/'),
        ('Resources/Img/plus.png', 'Resources/Img/'),
        ('Resources/Img/singleplayer.png', 'Resources/Img/'),
        ('Resources/Img/soleil_default.jpg', 'Resources/Img/'),
        ('configFile.toml', '.')
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Puppet Launcher',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['Resources/Img/default_icon.ico'],
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='puppet_launcher_v_0.0.1',
)